### ISSUE TITLE
Error when building WingetUI / Create wiki

### ISSUE THREAD

**Issue by ppvnf** [martinet101/WingetUI#163]
In the uninstall section I wish I could select/unselect some apps and then click "uninstall selected packages", like in the update section. 

Related: 
https://github.com/martinet101/WingetUI/issues/111
https://github.com/martinet101/WingetUI/issues/156

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/193123779-82903f80-fd9d-4b4f-bbf8-10ac5fcc7660.png)
That was impelemnted with the toolbar, and it will come with the next version.

**Comment by ppvnf** [comment]
awesome!

**Comment by ppvnf** [comment]
By looking at it I just don't understand the function of the lock beside "Uninstall selected". It looks like a version pin, but I know Winget doesn't have an equivalent to `scoop hold` yet

**Comment by martinet101** [comment]
> Also, I think it's an amazing feature to have, but I feel a little bit scared of clicking select all and then accidentally uninstall everything on my computer. How about a confirmation message showing the number of packages you wish to uninstall?

Yes, this i'm going to change it. Also, it will ask for confirmation.



> And just to be extra sure I, if I click select all after a search It won't select packages that aren't shown in the search, right?

Nope, all tyhe options apply only to the visible packages to the user

> PS. I want to build WingetUI to try it myself, but I'm getting an error. Tomorrow I will try to reinstall Python and Visual C++ to see if I am able to get it compiled.

Are you running Python 10 + latest PyInstaller?

**Comment by martinet101** [comment]
> By looking at the image the only thing I didn't understand was the lock beside "Uninstall selected". I wish it was a version pin, but I know Winget doesn't have an equivalent to `scoop hold` just yet.

I don't know if I understood you right, but you can blacklist app updates

**Comment by ppvnf** [comment]
> Are you running Python 10 + latest PyInstaller?

Yes, I am getting [this error](https://www.somepythonthings.tk/error-report/?appName=WingetUI&errorBody={s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}OS:{s}Windows{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Version:{s}(%2710%27,{s}%2710.0.19044%27,{s}%27SP0%27,{s}%27Multiprocessor{s}Free%27){l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}OS{s}Architecture:{s}AMD64{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}APP{s}Architecture:{s}64bit{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}APP{s}Version:{s}1.39{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Program:{s}WingetUI{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Program{s}section:{s}Main{s}script{l}{l}-----------------------------------------------------------------------------------------{l}{l}{l}{l}WingetUI%20Log:{l}{l}{l}{l}{l}Traceback{s}(most{s}recent{s}call{s}last):{l}{s}{s}File{s}__init__.py,{s}line{s}10,{s}in{s}%3Cmodule%3E{l}{s}{s}{s}{s}from{s}mainWindow{s}import{s}*{l}{s}{s}File{s}C:\Users\PICHAU\.wingetui\_MEI117002\mainWindow.py,{s}line{s}1,{s}in{s}%3Cmodule%3E{l}{s}{s}{s}{s}from{s}turtle{s}import{s}isvisible{l}{l}ModuleNotFoundError:{s}No{s}module{s}named{s}%27turtle%27%3Cclass{s}%27ModuleNotFoundError%27%3E:{s}No{s}module{s}named{s}%27turtle%27) message when clicking build_win.bat. I've already installed PySide6, win32mica and PyInstaller. When I run `python __init__.py` I get:

```
PS D:\Users\PICHAU\Downloads\WingetUI-main\wingetui> python __init__.py
Win32Mica Error: win32 version 19044 is not supported
Traceback (most recent call last):
  File "D:\Users\PICHAU\Downloads\WingetUI-main\wingetui\__init__.py", line 9, in <module>
    import wingetHelpers, scoopHelpers
  File "D:\Users\PICHAU\Downloads\WingetUI-main\wingetui\wingetHelpers.py", line 3, in <module>
    from tools import *
ModuleNotFoundError: No module named 'tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\PICHAU\Downloads\WingetUI-main\wingetui\__init__.py", line 1557, in <module>
    traceback_info += str(type(e))
NameError: name 'e' is not defined
PS D:\Users\PICHAU\Downloads\WingetUI-main\wingetui>
```


> I don't know if I understood you right, but you can blacklist app updates

Yes, I know. I just wished there was a native way to do that in Winget-CLI. Could you explain to me what the locker inside the blue circle is used for?

![193123779-82903f80-fd9d-4b4f-bbf8-10ac5fcc7660](https://user-images.githubusercontent.com/73800734/193368207-6f4d2527-805b-4218-8d29-32d1b0d41e9e.png)

**Comment by martinet101** [comment]
> Yes, I know. I just wished there was a native way to do that in Winget-CLI. Could you explain to me what the locker inside the blue circle is used for?

It is just an uninstall button

**Comment by martinet101** [comment]
Can you please check that the `tools.pt doesn't have the name in capital letters?`

**Comment by martinet101** [comment]
Because that was a faced issue by some people

**Comment by martinet101** [comment]
> Yes, I am getting [this error](https://www.somepythonthings.tk/error-report/?appName=WingetUI&errorBody=%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7DOS:%7Bs%7DWindows%7Bl%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7DVersion:%7Bs%7D(%2710%27,%7Bs%7D%2710.0.19044%27,%7Bs%7D%27SP0%27,%7Bs%7D%27Multiprocessor%7Bs%7DFree%27)%7Bl%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7DOS%7Bs%7DArchitecture:%7Bs%7DAMD64%7Bl%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7DAPP%7Bs%7DArchitecture:%7Bs%7D64bit%7Bl%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7DAPP%7Bs%7DVersion:%7Bs%7D1.39%7Bl%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7DProgram:%7Bs%7DWingetUI%7Bl%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7DProgram%7Bs%7Dsection:%7Bs%7DMain%7Bs%7Dscript%7Bl%7D%7Bl%7D-----------------------------------------------------------------------------------------%7Bl%7D%7Bl%7D%7Bl%7D%7Bl%7DWingetUI%20Log:%7Bl%7D%7Bl%7D%7Bl%7D%7Bl%7D%7Bl%7DTraceback%7Bs%7D(most%7Bs%7Drecent%7Bs%7Dcall%7Bs%7Dlast):%7Bl%7D%7Bs%7D%7Bs%7DFile%7Bs%7D__init__.py,%7Bs%7Dline%7Bs%7D10,%7Bs%7Din%7Bs%7D%3Cmodule%3E%7Bl%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7Dfrom%7Bs%7DmainWindow%7Bs%7Dimport%7Bs%7D*%7Bl%7D%7Bs%7D%7Bs%7DFile%7Bs%7DC:%5CUsers%5CPICHAU.wingetui_MEI117002%5CmainWindow.py,%7Bs%7Dline%7Bs%7D1,%7Bs%7Din%7Bs%7D%3Cmodule%3E%7Bl%7D%7Bs%7D%7Bs%7D%7Bs%7D%7Bs%7Dfrom%7Bs%7Dturtle%7Bs%7Dimport%7Bs%7Disvisible%7Bl%7D%7Bl%7DModuleNotFoundError:%7Bs%7DNo%7Bs%7Dmodule%7Bs%7Dnamed%7Bs%7D%27turtle%27%3Cclass%7Bs%7D%27ModuleNotFoundError%27%3E:%7Bs%7DNo%7Bs%7Dmodule%7Bs%7Dnamed%7Bs%7D%27turtle%27) message when clicking build_win.bat. I've already installed PySide6, win32mica and PyInstaller. When I run `python __init__.py` I get:

VSCode added again thia annoying import. gonna remove it

**Comment by ppvnf** [comment]
It is still capitalized. I've changed Tools.py to tools.py and the error is now the following:

```
PS D:\Users\PICHAU\Downloads\WingetUI-main\wingetui> python __init__.py
Win32Mica Error: win32 version 19044 is not supported
PS D:\Users\PICHAU\Downloads\WingetUI-main\wingetui>
```

When I open build.bat:

[cmd.txt](https://github.com/martinet101/WingetUI/files/9691062/cmd.txt)

```
  OS: Windows
                   Version: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: 1.4
                   Program: WingetUI
           Program section: Main script

-----------------------------------------------------------------------------------------



WingetUI Log:




Traceback (most recent call last):
  File __init__.py, line 10, in <module>
  File .\MainWindow.py, line 5, in <module>

ModuleNotFoundError: No module named 'win32gui'<class 'ModuleNotFoundError'>: No module named 'win32gui'
```

**Comment by martinet101** [comment]
change also `MainWindow` to `mainWindow`

**Comment by martinet101** [comment]
This is weird stuff with pywin32. 

You need to go to `C:\Users\{username}\AppData\Local\Programs\Python\Python310\Scripts`
and run `python pywin32_postinstall.py -install`

**Comment by ppvnf** [comment]
I tried it all, Python from Winget, MS Store and standalone... It feels like my PC just doesn't like WingetUI. Hopefully when I upgrade to Windows 11 things will improve.

```
PS C:\Users\PICHAU\AppData\Local\Programs\Python\Python310\Scripts> python pywin32_postinstall.py -install
C:\Users\PICHAU\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Users\\PICHAU\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\pywin32_postinstall.py': [Errno 2] No such file or directory
PS C:\Users\PICHAU\AppData\Local\Programs\Python\Python310\Scripts>
```

```
PS D:\Users\PICHAU\Downloads\WingetUI-main\wingetui> python __init__.py
Win32Mica Error: win32 version 19044 is not supported
```

[cmd.txt](https://github.com/martinet101/WingetUI/files/9691432/cmd.txt)


```
 OS: Windows
                   Version: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: 1.4
                   Program: WingetUI
           Program section: Main script

-----------------------------------------------------------------------------------------



WingetUI Log:




Traceback (most recent call last):
  File D:\Users\PICHAU\Downloads\WingetUI-main\wingetui\__init__.py, line 10, in <module>
    from mainWindow import *
  File D:\Users\PICHAU\Downloads\WingetUI-main\wingetui\mainWindow.py, line 5, in <module>
    import win32gui

ModuleNotFoundError: No module named 'win32gui'<class 'ModuleNotFoundError'>: No module named 'win32gui'
```

**Comment by martinet101** [comment]
Are you running the latest version of pywin32? remember not to install win32gui but rather pywin32

**Comment by ppvnf** [comment]
I've managed to launch it after running `python __init__.py`. Changes I've made: 

- rename Tools.py to tools.py
- rename MainWindow.py to mainWindow.py
- add pywin32 to requirements.txt
- pwshell execute 

```
git config --global --add safe.directory C:/Users/PICHAU/scoop/buckets/

git config --global --add safe.directory C:/Users/PICHAU/scoop/buckets/extras

git config --global --add safe.directory C:/Users/PICHAU/scoop/buckets/main
```

However icons and Winget packages are missing:

![Captura de tela 2022-10-02 183109](https://user-images.githubusercontent.com/73800734/193477144-351d1bb2-8b71-420a-93bc-5c343e2b2782.png)

```
PS D:\Users\PICHAU\Downloads\WingetUI-main(1)\WingetUI-main\wingetui> python __init__.py
Win32Mica Error: win32 version 19044 is not supported
Unknown option "darkmode=0"
O sistema não pode encontrar o caminho especificado.
O sistema não pode encontrar o caminho especificado.
O sistema não pode encontrar o caminho especificado.
b'O sistema n\xc6o pode encontrar o caminho especificado.'
O sistema no pode encontrar o caminho especificado.
b'O sistema n\xc6o pode encontrar o caminho especificado.'
O sistema no pode encontrar o caminho especificado.

```



build.bat didn't work, but I'm using Windows Store version of Python 3.10:

```
OS: Windows
                   Version: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: 1.4
                   Program: WingetUI
           Program section: Main script

-----------------------------------------------------------------------------------------



WingetUI Log:




Traceback (most recent call last):
  File __init__.py, line 10, in <module>
  File PyInstaller\loader\pyimod02_importers.py, line 499, in exec_module
  File .\mainWindow.py, line 5, in <module>

ImportError: DLL load failed while importing win32gui: Não foi possível encontrar o módulo especificado.<class 'ImportError'>: DLL load failed while importing win32gui: Não foi possível encontrar o módulo especificado
```

**Comment by ppvnf** [comment]
I've created a pull request #184

**Comment by ppvnf** [comment]
@martinet101, I've changed the name of this issue. Shouldn't it be reopen? I know we went completely off topic, but I am thankful about that since it helped me fix https://github.com/martinet101/WingetUI/issues/92. It feels like I am missing just a single thing to be able to properly build WingetUI tho...

Also, what do you think about adding to the readme a guide to help other newbies like me build WingetUI?

If you wish I can adapt and add https://github.com/martinet101/ElevenClock/wiki#running-and-building-the-source-code after the screenshots in the readme.

**Comment by martinet101** [comment]
> Also, what do you think about adding to the readme a guide to help other newbies like me build WingetUI?

yeah, definitely. Do you have rights to edit the wiki?

**Comment by ppvnf** [comment]
This has only been partially fixed. Icons/winget packages are still missing https://github.com/martinet101/WingetUI/issues/163#issuecomment-1264737794.

**Comment by ppvnf** [comment]
@martinet101 I've created the wiki https://github.com/ppvnf/WingetUI/wiki and also added a small FAQ

**Comment by martinet101** [comment]
Wow thank you!

Can you please pullrequest to the repo so you can get the credits of the wiki?

**Comment by ppvnf** [comment]
> Wow thank you!
> 
> Can you please pullrequest to the repo so you can get the credits of the wiki?

Sure!

**Comment by martinet101** [comment]
Can you edit it now?

**Comment by ppvnf** [comment]
> Can you edit it now?

yes!

**Comment by ppvnf** [comment]
Should I close this issue, since I am now able to build WingetU using build.bat? I don't think it matters much, but running `python __init__.py` still doesn't display icons and build.bat isn't generating an .exe file...

**Comment by martinet101** [comment]
> build.bat isn't generating an .exe file

this is expected, it generates a folder with the executable and its requirements

**Comment by martinet101** [comment]
> Should I close this issue [...]?

I guess so
